import React from 'react';

export default function Disclaimer() {
  return (
    <div className="legal-page">
      <h1>Disclaimer</h1>
      <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
      
      <h2>1. General Information</h2>
      <p>The information provided by Harshz Technologies Private Limited on this platform is for general informational purposes only related to green building automation (GRIHA, IGBC).</p>
      
      <h2>2. No Professional Advice</h2>
      <p>The data and insights generated by this platform do not constitute professional engineering or legal advice. Please consult certified green building professionals before making critical infrastructure decisions.</p>

      <h2>3. “As Is” Delivery</h2>
      <p>All information on the site is provided in good faith, however, we make no representation or warranty of any kind regarding the accuracy or completeness of the automation tools.</p>

      <h2>4. Contact</h2>
      <p>Company: Harshz Technologies Private Limited</p>
      <p>Founder: Harsh Langeh</p>
      <p>Email: contact@harshz.com</p>
    </div>
  );
}
